# Generated by Django 5.1.1 on 2024-09-22 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='packages',
        ),
        migrations.AddField(
            model_name='package',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travellers',
            name='interests',
            field=models.ManyToManyField(blank=True, to='core.label'),
        ),
    ]
