# Generated by Django 5.1.1 on 2024-09-23 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.guide'),
        ),
    ]
