# Generated by Django 5.1.1 on 2024-09-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_package_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.guide'),
        ),
    ]
