# Generated by Django 5.1.1 on 2024-09-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_package_business_package_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/giude/profile'),
        ),
    ]
