# Generated by Django 5.1.1 on 2024-09-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_created_at_alter_event_img_post_postcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.ManyToManyField(blank=True, to='core.label'),
        ),
    ]
