# Generated by Django 5.1.1 on 2024-09-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_packagesubscription_subscribed_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packagesubscription',
            unique_together={('package', 'subscribed_by')},
        ),
    ]
