# Generated by Django 5.1.1 on 2024-09-24 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_packagesubscription_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagecomment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.package'),
        ),
    ]
