# Generated by Django 5.1.1 on 2024-09-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eventcomment_packagecomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventLike',
            new_name='EventInterested',
        ),
        migrations.RenameField(
            model_name='eventinterested',
            old_name='liked_by',
            new_name='interested_user',
        ),
        migrations.DeleteModel(
            name='EventComment',
        ),
    ]
